export const COMMON_CNAES = [
  { code: '4781-4/00', description: 'Comércio varejista de artigos do vestuário e acessórios', annex: 'I', fator_r: false },
  { code: '4789-0/99', description: 'Comércio varejista de outros produtos não especificados anteriormente', annex: 'I', fator_r: false },
  { code: '5611-2/01', description: 'Restaurantes e similares', annex: 'I', fator_r: false },
  { code: '5611-2/03', description: 'Lanchonetes, casas de chá, de sucos e similares', annex: 'I', fator_r: false },
  { code: '4772-5/00', description: 'Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal', annex: 'I', fator_r: false },
  { code: '4755-5/02', description: 'Comercio varejista de artigos de armarinho', annex: 'I', fator_r: false },
  { code: '4744-0/99', description: 'Comércio varejista de materiais de construção em geral', annex: 'I', fator_r: false },
  { code: '4754-7/01', description: 'Comércio varejista de móveis', annex: 'I', fator_r: false },
  { code: '4751-2/01', description: 'Comércio varejista especializado de equipamentos e suprimentos de informática', annex: 'I', fator_r: false },
  { code: '4782-2/01', description: 'Comércio varejista de calçados', annex: 'I', fator_r: false },
  { code: '4721-1/02', description: 'Padaria e confeitaria com predominância de revenda', annex: 'I', fator_r: false },
  { code: '4753-9/00', description: 'Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo', annex: 'I', fator_r: false },
  { code: '4729-6/99', description: 'Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente', annex: 'I', fator_r: false },
  { code: '4712-1/00', description: 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - minimercados, mercearias e armazéns', annex: 'I', fator_r: false },
  { code: '4771-7/01', description: 'Comércio varejista de produtos farmacêuticos, sem manipulação de fórmulas', annex: 'I', fator_r: false },
  
  // Services (Annex III mostly)
  { code: '9602-5/01', description: 'Cabeleireiros, manicure e pedicure', annex: 'III', fator_r: false },
  { code: '9602-5/02', description: 'Atividades de estética e outros serviços de cuidados com a beleza', annex: 'III', fator_r: false },
  { code: '4330-4/04', description: 'Serviços de pintura de edifícios em geral', annex: 'III', fator_r: false },
  { code: '4321-5/00', description: 'Instalação e manutenção elétrica', annex: 'III', fator_r: false },
  { code: '4322-3/01', description: 'Instalações hidráulicas, sanitárias e de gás', annex: 'III', fator_r: false },
  { code: '9511-8/00', description: 'Reparação e manutenção de computadores e de equipamentos periféricos', annex: 'III', fator_r: false },
  { code: '9521-5/00', description: 'Reparação e manutenção de equipamentos eletroeletrônicos de uso pessoal e doméstico', annex: 'III', fator_r: false },
  { code: '7420-0/01', description: 'Atividades de produção de fotografias, exceto aérea e submarina', annex: 'III', fator_r: false },
  { code: '7490-1/04', description: 'Atividades de intermediação e agenciamento de serviços e negócios em geral, exceto imobiliários', annex: 'III', fator_r: false },
  { code: '7739-0/02', description: 'Aluguel de equipamentos científicos, médicos e hospitalares, sem operador', annex: 'III', fator_r: false },
  { code: '8211-3/00', description: 'Serviços combinados de escritório e apoio administrativo', annex: 'III', fator_r: false },
  { code: '8219-9/99', description: 'Preparação de documentos e serviços especializados de apoio administrativo não especificados anteriormente', annex: 'III', fator_r: false },
  { code: '8230-0/01', description: 'Serviços de organização de feiras, congressos, exposições e festas', annex: 'III', fator_r: false },
  { code: '9329-8/99', description: 'Outras atividades de recreação e lazer não especificadas anteriormente', annex: 'III', fator_r: false },
  { code: '8599-6/04', description: 'Treinamento em desenvolvimento profissional e gerencial', annex: 'III', fator_r: false },
  { code: '8592-9/99', description: 'Ensino de arte e cultura não especificado anteriormente', annex: 'III', fator_r: false },
  { code: '4930-2/02', description: 'Transporte rodoviário de carga, exceto produtos perigosos e mudanças, intermunicipal, interestadual e internacional', annex: 'III', fator_r: false },
  { code: '4923-0/02', description: 'Serviço de transporte de passageiros - locação de automóveis com motorista', annex: 'III', fator_r: false },
  
  // Subject to Fator R (Annex III or V)
  { code: '6201-5/01', description: 'Desenvolvimento de programas de computador sob encomenda', annex: 'V', fator_r: true },
  { code: '6202-3/00', description: 'Desenvolvimento e licenciamento de programas de computador customizáveis', annex: 'V', fator_r: true },
  { code: '6204-0/00', description: 'Consultoria em tecnologia da informação', annex: 'V', fator_r: true },
  { code: '6920-6/01', description: 'Atividades de contabilidade', annex: 'III', fator_r: false }, // Exception: always annex III
  { code: '7111-1/00', description: 'Serviços de arquitetura', annex: 'V', fator_r: true },
  { code: '7112-0/00', description: 'Serviços de engenharia', annex: 'V', fator_r: true },
  { code: '7311-4/00', description: 'Agências de publicidade', annex: 'V', fator_r: true },
  { code: '7410-2/03', description: 'Design de produto', annex: 'V', fator_r: true },
  { code: '7490-1/01', description: 'Serviços de tradução, interpretação e similares', annex: 'V', fator_r: true },
  { code: '8630-5/03', description: 'Atividade médica ambulatorial restrita a consultas', annex: 'V', fator_r: true },
  { code: '8630-5/04', description: 'Atividade odontológica', annex: 'V', fator_r: true },
  { code: '8640-2/02', description: 'Laboratórios clínicos', annex: 'V', fator_r: true },
  { code: '8650-0/01', description: 'Atividades de enfermagem', annex: 'V', fator_r: true },
  { code: '8650-0/04', description: 'Atividades de fisioterapia', annex: 'V', fator_r: true },
  { code: '8650-0/03', description: 'Atividades de psicologia e psicanálise', annex: 'V', fator_r: true },
  { code: '8650-0/02', description: 'Atividades de fonoaudiologia', annex: 'V', fator_r: true },
  { code: '7500-1/00', description: 'Atividades veterinárias', annex: 'V', fator_r: true },
];
